# Generated by Django 4.2.5 on 2023-09-30 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=10, null=True)),
                ('favorite_color', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_prompt', models.TextField(editable=False, help_text='The prompt that starts the story.')),
                ('content', models.TextField(editable=False, help_text='The total content of the story.')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_by', models.CharField(choices=[('bot', 'Bot'), ('reader', 'Reader')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jurni.reader')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jurni.story')),
            ],
        ),
    ]
